_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 23
                - 24
                - 55
            "4": 3.10.5
            "5": 0.19.1
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.1
            "13": windows-amd64
